### ISSUE TITLE
Build fails when using specific build directory

### ISSUE THREAD

**Issue by LiohAu** [jverkoey/iOS-Framework#29]
I'm building this framework using two ways : 
- my Xcode
- A continuous integration tool (jenkins in my case)

When building from xcode everything is fine, but when building from jenkins the shell script fails and i'm getting the following message : 

"Could not find platform name from build products directory: /Users/X/Desktop/workspace/Project-Name/build"

I tried to echo the $BUILT_PRODUCTS_DIR and $SF_SDK_PLATFORM vars, and when using the CI tool i get something like : 

BUILT_PRODUCTS_DIR = /Users/X/Desktop/workspace/Project-Name/build
SF_SDK_PLATFORM = iphoneos

whereas from Xcode i'm getting this :

BUILT_PRODUCTS_DIR = /Users/Y/Library/Developer/Xcode/DerivedData/Project-Name-bzuxlzzqgtqufzfofmkedmdiphnm/Build/Products/Release-iphoneos
SF_SDK_PLATFORM = iphoneos

I assume it is the "CONFIGURATION_BUILD_DIR" xcodebuild parameter which cause the problem, since i can't build in the same place in my CI tool, but i don't know how can i change the script to make it works in any case. I would like to do not hardcode some vars.

PS : I can't change the script executed in the CI tool to make it use BUILD_DIR instead of CONFIGURATION_BUILD_DIR

**Comment by joshlytle** [comment]
Just add "Release-iphoneos" to the custom build directory you are specifying. So "[your path]/build/Release-iphoneos" for example.
