### ISSUE TITLE
Addind a Third-Party Framework to the iOS-Framework

### ISSUE THREAD

**Issue by loretoparisi** [jverkoey/iOS-Framework#83]
Supposed to add a 3rd-Party framework the iOS-Framework, how to export this in the generated framework?
Let's say the Serenity framework project has a External.framework. As soon as I build the Serenity.framework linking the External.framework ( I added this .framework to the "Link Binary With Libraries") and add it to the Third Party example app, I have got an error:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SBNotificationHub", referenced from:
      objc-class-ref in Serenity(Widget.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

that is the object defined in the static framework External.framework I'm linking by the Serenity.framework in the ThirdParty app.

So far I have to import again the External.framework inside the  ThirdParty project to make it work properly.

**Comment by Radhika-Geek** [comment]
@GSatko Can you please explain how to use this script and where.
